parse_config:
  zmk_keycode_map:
    # arrows (include tokens and common variants)
    UP: "🞁"
    DOWN: "🞃"
    LEFT: "🞀"
    RIGHT: "🞂"
    KC_UP: "🞁"
    KC_DOWN: "🞃"
    KC_LEFT: "🞀"
    KC_RIGHT: "🞂"
    ARROW_UP: "🞁"
    ARROW_DOWN: "🞃"
    ARROW_LEFT: "🞀"
    ARROW_RIGHT: "🞂"

    # volume
    VOLUP: "🔊"
    VOLDN: "🔉"
    VOL_UP: "🔊"
    VOL_DN: "🔉"
    VOL_DOWN: "🔉"
    VOLUME_UP: "🔊"
    VOLUME_DOWN: "🔉"
    C_VOL_UP: "🔊"
    C_VOL_DN: "🔉"
    KC_VOL_UP: "🔊"
    KC_VOL_DOWN: "🔉"

    # brightness
    BRI_UP: "🔆"
    BRI_DN: "🔅"
    BRI_UPPER: "🔆"
    BRI_DOWN: "🔅"
    BRIGHTNESS_UP: "🔆"
    BRIGHTNESS_DOWN: "🔅"
    C_BRI_UP: "🔆"
    C_BRI_DN: "🔅"
    KC_BRI_UP: "🔆"
    KC_BRI_DN: "🔅"
    KC_BRIGHTNESS_UP: "🔆"
    KC_BRIGHTNESS_DOWN: "🔅"

    # misc
    SPACE: "␣"
    SPC: "␣"
    ENTER: "↵"
    RET: "↵"
    TAB: "⇥"
    DEL: "⌦"
    BSPC: "⌫"
    BACKSPACE: "⌫"
    ESC: "⎋"

    # modkeys
    CTRL: "⌃"
    LCTRL: "⌃"
    RCTRL: "⌃"
    GUI: "⌘"
    LGUI: "⌘"
    RGUI: "⌘"
    ALT: "⎇"
    LALT: "⎇"
    RALT: "⌥"
    SHFT: "⇧"
    SHIFT: "⇧"
    LSHFT: "⇧"
    RSHFT: "⇧"
    LSHIFT: "⇧"
    RSHIFT: "⇧"

    # punctuation
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: "\""
    DQT: "\""
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
