parse_config:
  zmk_keycode_map:
    # arrows (include tokens and common variants)
    UP: "↑"
    DOWN: "↓"
    LEFT: "←"
    RIGHT: "→"
    KC_UP: "↑"
    KC_DOWN: "↓"
    KC_LEFT: "←"
    KC_RIGHT: "→"
    ARROW_UP: "↑"
    ARROW_DOWN: "↓"
    ARROW_LEFT: "←"
    ARROW_RIGHT: "→"

    # volume
    VOL_UP: "🕪"
    VOLDN: "🕩"
    VOL_DN: "🕩"
    VOL_DOWN: "🕩"
    VOLUME_UP: "🕪"
    VOLUME_DOWN: "🕩"
    KC_VOL_UP: "🕪"
    KC_VOL_DOWN: "🕩"

    # brightness
    BRI_UP: "🔆"
    BRI_DN: "🔅"
    BRI_UPPER: "🔆"
    BRIGHTNESS_UP: "🔆"
    BRIGHTNESS_DOWN: "🔅"
    KC_BRI_UP: "🔆"
    KC_BRI_DOWN: "🔅"
    KC_BRIGHTNESS_UP: "🔆"
    KC_BRIGHTNESS_DOWN: "🔅"

    # (include previous mappings you have — ensure you merge, not overwrite)
    SPACE: "␣"
    SPC: "␣"
    ENTER: "↵"
    RET: "↵"
    TAB: "⇥"
    DEL: "⌦"
    BSPC: "⌫"
    BACKSPACE: "⌫"
    ESC: "⎋"
    LCTRL: "^"
    RCTRL: "^"
    LGUI: "❖"
    RGUI: "❖"
    LALT: "⎇"
    RALT: "⎇"
    LSHIFT: "⇧"
    RSHIFT: "⇧"

  raw_binding_map:
    # arrows
    "UP": "↑"
    "DOWN": "↓"
    "LEFT": "←"
    "RIGHT": "→"
    "KC_UP": "↑"
    "KC_DOWN": "↓"
    "KC_LEFT": "←"
    "KC_RIGHT": "→"

    # volume
    "VOL UP": "🕪"
    "VOL_UP": "🕪"
    "VOL DN": "🕩"
    "VOL_DN": "🕩"
    "VOLUME UP": "🕪"
    "VOLUME DOWN": "🕩"

    # brightness
    "BRI UP": "🔆"
    "BRI_UP": "🔆"
    "BRI DN": "🔅"
    "BRI_DN": "🔅"
    "BRIGHTNESS UP": "🔆"
    "BRIGHTNESS DOWN": "🔅"

    # (keep previous raw mappings)
    "SPACE": "␣"
    "SPC": "␣"
    "ENTER": "↵"
    "RET": "↵"
    "TAB": "⇥"
    "DEL": "⌦"
    "BSPC": "⌫"
    "BACKSPACE": "⌫"
    "ESC": "⎋"
